### ISSUE TITLE
Live Preview Support

### ISSUE THREAD

**Issue by arminta7** [gapmiss/badges#1]
Any plans to support live preview?

**Comment by gapmiss** [comment]
I can look into if it's possible and if so, what level of effort to implement. Thank you for the suggestion.

**Comment by WritwikRay** [comment]
+1

**Comment by rialistic** [comment]
+ 1 :)

**Comment by MugenLee** [comment]
+1

**Comment by gapmiss** [comment]
Happy to see so much interest in this plugin. Unfortunately, my project load outside of Obsidian plugin dev, has me occupied with other endeavors. I will leave this open on the chance that another developer might want to take on the task and implement "Live preview."

**Comment by The-Inamati** [comment]
+1 On this. Would be amazing.

**Comment by berot3** [comment]
I think most if not all are working most of the time in live preview. so this is actually a must have... sorry 👍 

I hope you will get many more coffees sponsored so we don't have to wait too long! ;)

**Comment by prods** [comment]
+1

**Comment by gapmiss** [comment]
@arminta7 @FelipeRearden @WritwikRay @rialistic @mitten @MugenLee @The-Inamati @berot3 

"Live Preview" support is now implemented.

Please open a new issue if any problems are encountered.

Enjoy!
